#user

login:
  url: /login
  param: { module: user, action: login }

logout:
  url: /logout
  param: { module: user, action: logout }

user_list:
  url: /user_list
  param: { module: user, action: list }

user_show:
  url: /user_show/:id
  param: { module: user, action: show }

#task

task_list:
  url: /task_list
  param: { module: task, action: list }

task_show:
  url: /task_show/:id
  param: { module: task, action: show }

task_ajax:
  url: /task_ajax
  param: { module: task, action: ajax }


# default rules
homepage:
  url:   /
  param: { module: top, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
