default:
  http_metas:
    content-type: text/html

  metas:
    title:        Progate Camp
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [common, main, top, bootstrap]

  javascripts:    []

  has_layout:     on
  layout:         layout
