default:
  http_metas:
    content-type: text/html

  metas:
    title:        Progate Camp | 9週間・500時間の超集中型プログラミングキャンプ
    robots:       index, follow
    description:  Progate Campは9週間・500時間の超集中型プログラミングキャンプです。WEBサービスを自分で作り上げながら、プログラミングを習得します。
    keywords:     Progate, Camp, プログラミング, Ruby On Rails, Ruby, HTML, CSS, 初心者, キャンプ, Git
    language:     en

  stylesheets:    [main, top, bootstrap]

  javascripts:    []

  has_layout:     on
  layout:         layout
