<?php
// auto-generated by sfPropelCrud
// date: 2014/10/22 16:38:29
?>
<?php use_helper('Object', 'DateForm') ?>

<?php echo form_tag('task/update') ?>

<?php echo object_input_hidden_tag($task, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($task, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($task, 'getBody', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Due Date:</th>
  <td>
    <?php echo select_year_tag('year', '1980', array('year_start' => date('Y'), 'year_end' => '1910')) ?>年
    <?php echo select_month_tag('month', '1', array('use_month_numbers'=>true)) ?>月
    <?php echo select_day_tag('day', '1') ?>日
  </td>
</tr>
<tr>
  <th>Display:</th>
  <td><?php echo object_input_tag($task, 'getDisplay', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($task->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'task/delete?id='.$task->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'task/show?id='.$task->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'task/list') ?>
<?php endif; ?>
</form>
