<?php
// auto-generated by sfPropelCrud
// date: 2014/10/22 16:38:29
?>
<table>
<tbody>
<tr>
<th>Title: </th>
<td><?php echo $task->getTitle() ?></td>
</tr>
<tr>
<th>Body: </th>
<td><?php echo $task->getBody() ?></td>
</tr>
<tr>
<th>Completed users: </th>
<td><?php echo $task->getCompletedUsers() ?></td>
</tr>
<tr>
<th>Display: </th>
<td><?php echo $task->getDisplay() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $task->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $task->getUpdatedAt() ?></td>
</tr>
<tr>
<th>Id: </th>
<td><?php echo $task->getId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'task/edit?id='.$task->getId()) ?>
&nbsp;<?php echo link_to('list', 'task/list') ?>
