propel:
  user:
    name: varchar(60)
    kana: varchar(60)
    birthday: timestamp
    gender: varchar(20)
    email: varchar(60)
    phone_number: varchar(20)
    background: varchar(60)
    reason: longvarchar
    prospect: longvarchar
    confirm: { type: integer, default: 0 }
    facebook_id: varchar(255)
    twitter_id: varchar(255)
    display: integer
    created_at:
    updated_at:
